### ISSUE TITLE
All audits should be configured solely on the contents of the .toml

### ISSUE THREAD

**Issue by diogomonica** [diogomonica/actuary#2]
The code currently has:

```
    for category := range tomlProfile.Audit {
        switch auditName = tomlProfile.Audit[category].Name; auditName {
        case "Host Configuration":
            actions = dockerhost.GetAuditDefinitions()      
        case "Docker daemon configuration":
            actions = dockerconf.GetAuditDefinitions()
        case "Docker daemon configuration files":
            actions = dockerfiles.GetAuditDefinitions()
        case "Container Images and Build File" :
            actions = images.GetAuditDefinitions()
        case "Container Runtime" :
            actions = runtime.GetAuditDefinitions()
        case "Docker Security Operations" :
            actions = dockersecops.GetAuditDefinitions()
        default: 
            log.Panicf("No audit category named:", auditName)
            continue
        }
```

We can probably find a way of not having to do this switch, and simply load all of the tests that are matching the file (so we can in theory move tests from one place to the other without code changes).

**Comment by zuBux** [comment]
I'm trying to find a way to do this. Even if make checks independent from their categories (which might be a good idea) I still think that a map will be required. If we try to dynamically call functions from the TOML profile (e.g `kernel_version` is transformed into `kernel_version()`), it would cause instability problems when handling malformed profiles.

**Comment by diogomonica** [comment]
Well, let's focus on simplicity of reading the checks/finding them on the code structure/adding new tests and categories.
