### ISSUE TITLE
Migrate to CIS Security Benchmark 1.11

### ISSUE THREAD

**Issue by zuBux** [diogomonica/actuary#8]
Since the new benchmark for Docker 1.11 has been released, we should review the checks made by Actuary.

**Comment by thanasisk** [comment]
Do you have a URL for the new benchmark?

**Comment by zuBux** [comment]
Fixed in https://github.com/diogomonica/actuary/commit/0d4f4c3feffbc092a293c4fbf45563036eacc848 through https://github.com/diogomonica/actuary/commit/a05ec02ec12aa5d9dfe479cc30aac38ad931d047
